#Server参数配置
server:
  #web端口
  port: 9010
  #线程参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 8
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载,默认io线程*8
    worker-threads: 200
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
#Spring参数
spring:
  application:
    # 应用名
    name: ensemble-im-service
  jackson:
    deserialization:
      USE_BIG_DECIMAL_FOR_FLOATS: true
    time-zone: GMT+8
    date-format: yyyyMMdd
  profiles:
    # 选择应用所使用的环境对应参数 dev,fat,sit,uat
    active: dev
  #Spring Batch参数
  batch:
    initialize-schema: always
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      #初始化物理连接个数
      initial-size: 20
      #最小连接池数量
      min-idle: 20
      #最大连接池数量
      max-active: 200
      # 配置获取连接等待超时的时间
      max-wait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句,如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
      validation-query: SELECT 'X' FROM DUAL
      #申请连接的时候检测，如果空闲时间大于imeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # 监控统计用的filter:stat
      # 日志用的filter:slf4j
      # 防御sql注入的filter:wall
      filters: stat,wall,config
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: 20
      #最小空闲连接数保活
      keep-alive: true
      #以下为基于spring boot web的内嵌druid监控，若需开启请将三个值均置为true
      stat-view-servlet:
        enabled: true
        allow: ""       #允许远程访问
      #WebStatFilter配置 是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
  #Servlet文件上传
  servlet:
    multipart:
      # 文件最大限制
      max-file-size: 100MB
      # 请求最大限制
      max-request-size: 100MB
      enabled: true
      # 设置文件缓存的临界点,超过则先保存到临时目录,默认为0,所有文件都会进行缓存
      file-size-threshold: 0
#Logback配置
logging:
  #logback地址
  config: classpath:logback-spring.xml
#eureka配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    health-check-url-path: /actuator/health
    metadata-map:
      management:
        context-path: /actuator
  client:
    register-with-eureka: true
    healthcheck:
      enabled: false
    eurekaServiceUrlPollIntervalSeconds: 60
#
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    redis:
      enabled: true

mybatis:
  mapper-locations: classpath*:META-INF/mapper/**/*.xml,classpath*:mapper/*.xml,classpath*:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

comet:
  flow:
    #此处query-time-out配置应与mybatis-config.xml中的queryTimeOut保持一致
    query-time-out: 180
    max-row: 20000      #sql查询最大条数
    fieldValid: true  # 大V注解校验开关
    field-head-valid: false  #报文头大V校验开关
  sequence:
    mars:
      enable: false

# feign 配置
feign:
  hystrix:
    enabled: true
  client:
    config:
      #服务名，填写default为所有服务
      default:
        # 连接超时
        connectTimeout: 60000
        # 响应超时
        readTimeout: 60000
        loggerLevel: basic
  httpclient:
    # 让feign使用Apache HTTPClient做请求，而不是默认的urlConnection
    enabled: true
    # feign最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

# hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            interruptOnTimeout: false
        timeout:
          enabled: true
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100
  threadpool:
    default:
      #并发执行的最大线程数，默认10
      coreSize: 10
      # 线程存活时间，单位是分钟。默认值为1。
      keepAliveTimeMinutes: 1
      # BlockingQueue的最大队列数，当设为-1，会使用SynchronousQueue，值为正时使用LinkedBlcokingQueue。
      maxQueueSize: -1
      # 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝。-1不生效
      queueSizeRejectionThreshold: -1

#Ribbin超时设置
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

# RestTemplate 相关参数
remote:
  #/* 连接池的最大连接数默认为0 */
  maxTotalConnect: 1
  #/* 单个主机的最大连接数 */
  maxConnectPerRoute: 200
  #/* 连接超时默认2s */
  connectTimeout: 120000
  #/* 读取超时默认30s */
  readTimeout: 180000
